### ISSUE TITLE
Score System

### ISSUE THREAD

**Issue by pgrenon1** [majetteleger/FMRSnake#10]
Should there be a score system?

**Comment by majetteleger** [comment]
on zone clear : score += length of snake * zone_constant

?

**Comment by majetteleger** [comment]
Functional, needs saving + UI display

**Comment by pgrenon1** [comment]
Saving and UI display done, not thoroughly tested + needs a way to have a modular entry count instead of a fixed one.

**Comment by majetteleger** [comment]
This is done, although it might need some balancing
