### ISSUE TITLE
Handle the beat

### ISSUE THREAD

**Issue by pgrenon1** [majetteleger/FMRSnake#13]

**Comment by pgrenon1** [comment]
Wouldn't be ready to close this yet, but there is a beat indicator now.

**Comment by majetteleger** [comment]
Different beat/zone transition (keep tempo)
- Wait until end of beat to change (This is done, but requires testing still, I think, please tell me if it works according to what you were expecting)
(success check: if the "different" beat was the same, there would be no gap)

**Comment by pgrenon1** [comment]
There sometimes is a beat repeat when changing Bar

**Comment by pgrenon1** [comment]
Sonner le Beat, pas seulement le metronome
