### ISSUE TITLE
UI update

### ISSUE THREAD

**Issue by majetteleger** [majetteleger/FMRSnake#15]
What the "final" game would look like

**Comment by majetteleger** [comment]
Main missing pieces:
- Controls showcase for each state (DONE)
- Indicate zone positions (DONE)
- Death screen (DONE*)
- In-game score display (DONE)
- Leaderboard display (DONE)

done = functional, not final. Will require a pass of polish

* Add some info to the "enter your name" screen, this is pretty much the death screen

**Comment by pgrenon1** [comment]
Beat Indicator works
