### ISSUE TITLE
Grid and zone generation

### ISSUE THREAD

**Issue by majetteleger** [majetteleger/FMRSnake#2]
Generate an interestingly shaped grid for the player to play on, as well as smaller zone that affect the game once the player is inside them

**Comment by majetteleger** [comment]
De-modify the zones after a time
Keep the stacking effects of the remaining zone modifiers

**Comment by pgrenon1** [comment]
FYI : your GridCell class now has a Content field that keeps track of what the cell holds. It is used to make sure that we don't spawn food on the player or on food.

**Comment by pgrenon1** [comment]
Ya tu une raison pourquoi le grid playground est responsable de spawner le joueur? à ce point-ci on devrait pas faire une game manager qui spawn le joueur et la grid?

**Comment by pgrenon1** [comment]
Ah I think I just understood why. C'est parce que tu spawn le player dans la cell centrale et tu veux pas avoir à faire deux itérations dans toute la grille! makes sense!

**Comment by majetteleger** [comment]
- Fuck le stacking for now
- Find a way to make this work without a visible grid
- Balance the spawn/despawn rate + find some prototype examples
