### ISSUE TITLE
Final balance

### ISSUE THREAD

**Issue by majetteleger** [majetteleger/FMRSnake#23]
- Map size / grid cell size
- Zone radius / spawn rate / max count / food count
- Standard / zones beats
- Overall speed / ramp up
- Obstacle shapes / spawn rate / max count

**Comment by pgrenon1** [comment]
- plus vite
- plus de bouffe
- score values

**Comment by pgrenon1** [comment]
- scale everything down
- tempo goes up with time

**Comment by majetteleger** [comment]
not really balance but dont want to open an issue for this: speed up death time?
