### ISSUE TITLE
Spawning of the tail isnt adapted to the grid

### ISSUE THREAD

**Issue by majetteleger** [majetteleger/FMRSnake#3]

**Comment by pgrenon1** [comment]
So, quand tu as mis le player en prefab qui spawn at Start(), fallait pas mettre la tail en tant que child du player, as weird as this sounds, parce que on veut pas que le transform de Player Tail suive le player dans ses mouvements.
![2018-06-23_10-43-08](https://user-images.githubusercontent.com/35233201/41810815-4ddfa4be-76d2-11e8-9ca9-ced1a157faa9.gif)

**Comment by pgrenon1** [comment]
Je vais essayer de faire qqch de plus adapté à la grid

**Comment by pgrenon1** [comment]
Created a Segment script to hold a ref to the current cell of each segments so that movement is not based on coordinates but on the actual position of gridCells.
Segment also takes care of moving each segments of the tail
