### ISSUE TITLE
Difficulty curve (hurt + death)

### ISSUE THREAD

**Issue by majetteleger** [majetteleger/FMRSnake#6]
What brings the player(s) closer to stopping the play session?
- Incremental/exponential difficulty curve until impossibl

**Comment by majetteleger** [comment]
Segments-- on failed move
death when snake too small

**Comment by pgrenon1** [comment]
J'pense que ce serait mieux de pas perdre complètement ton multiplier quand tu manque un mouvement, genre qu'il descende à chaque beat raté plutôt que tomber all the way à x1 à la première erreur.

**Comment by pgrenon1** [comment]
Ce serait peut-être aussi mieux ça prennent quelques mouvement de suite pour augmenter le multiplier. à moins qu'on veuille que ça aille à plus que x10
