### ISSUE TITLE
Error on death sequence, see details

### ISSUE THREAD

**Issue by pgrenon1** [majetteleger/FMRSnake#61]
MissingReferenceException: The object of type 'Segment' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
Player+<DoDie>c__Iterator0.MoveNext () (at Assets/Scripts/Player/Player.cs:355)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

**Comment by majetteleger** [comment]
te rappelle tu si cetait PENDANT que le snake shrinkait que tu as eu l'erreur, ou APRES qu'il ai tout shrinké?

**Comment by pgrenon1** [comment]
C'était dès le début de la séquence

**Comment by pgrenon1** [comment]
MissingReferenceException: The object of type 'SpriteRenderer' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Component.GetComponent[SpriteRenderer] () (at C:/buildslave/unity/build/Runtime/Export/Component.bindings.cs:42)
Player.PulseHeadSegment () (at Assets/Scripts/Player/Player.cs:565)
ActiveBeat.OnTriggerEnter2D (UnityEngine.Collider2D other) (at Assets/Scripts/UI/ActiveBeat.cs:62)

Maintenant j'ai cet erreur quand je meurt, ça arrive au début de la séquence de mort du player. Le snake a le temps de commencé l'animation de shrink

**Comment by pgrenon1** [comment]
Update: je crois que ça arrive au moment ou l'animation de shrink du player arrive à un point blanc. I guess que ya une référence callé à un point blanc qui est déjà détruit?
